/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.6 ***
*/

package net.minecraft.src;
import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class YC_wgPyramid extends WorldGenerator
{
	protected int[] GetValidSpawnBlocks() {
		return new int[] {
			Block.grass.blockID,
			Block.tallGrass.blockID,
			Block.snow.blockID
		};
	}

	public boolean LocationIsValidSpawn(World world, int i, int j, int k){
		/*int distanceToAir = 0;
		int checkID = world.getBlockId(i, j, k, 0, 3);

		while (checkID != 0){
			distanceToAir++;
			checkID = world.getBlockId(i, j + distanceToAir, k, 0, 3);
		}

		if (distanceToAir > 1){
			return false;
		}
		j += distanceToAir - 1;*/

		int blockID = world.getBlockId(i, j, k);
		int blockIDAbove = world.getBlockId(i, j+1, k);
		int blockIDBelow = world.getBlockId(i, j-1, k);
		for (int x : GetValidSpawnBlocks()){
			//if (blockIDAbove != 0){
			//	return false;
			//}
			if (blockID == x){
				return true;
			}else if (blockID == Block.snow.blockID && blockIDBelow == x){
				return true;
			}
		}
		return false;
	}

	public YC_wgPyramid() { }

	public boolean generate(World world, Random rand, int i, int j, int k) {
		//check that each corner is one of the valid spawn blocks
		//if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 18, j, k) || !LocationIsValidSpawn(world, i + 18, j, k + 21) || !LocationIsValidSpawn(world, i, j, k + 21))
		if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 16, j, k) || !LocationIsValidSpawn(world, i + 16, j, k + 19) || !LocationIsValidSpawn(world, i, j, k + 19))
		{
			return false;
		}

		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 5, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 6, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 18, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 19, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 5, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 10, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 19, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 15, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 8, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 18, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 11, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 6, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 15, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 7, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 7, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 7, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 7, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 7, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 3, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 18, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 7, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 7, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 8, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 8, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 8, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 2, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 3, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 9, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 12, YC_Mod.b_pyramidBrick.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 1, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 7, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 7, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 8, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 8, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 3, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 7, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 7, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 8, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 8, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 8, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 7, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 7, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 7, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 7, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 7, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 7, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 12, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 15, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 17, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 6, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 9, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 0, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 1, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 14, j + 4, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 5, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 13, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 16, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 0, k + 19, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 15, j + 3, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 5, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 6, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 18, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 0, k + 19, Block.cobblestone.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 2, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 4, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 5, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 6, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 7, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 8, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 9, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 10, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 11, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 12, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 13, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 14, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 15, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 16, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 17, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 18, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 19, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 17, j + 1, k + 20, Block.cobblestoneMossy.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 5, Block.torchWood.blockID, 5, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 19, Block.torchWood.blockID, 5, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 7, k + 12, Block.torchWood.blockID, 1, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 7, k + 11, Block.torchWood.blockID, 3, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 7, k + 13, Block.torchWood.blockID, 4, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 7, k + 12, Block.torchWood.blockID, 2, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 1, k + 5, Block.torchWood.blockID, 5, 3);
		world.setBlockAndMetadataWithNotify(i + 16, j + 1, k + 19, Block.torchWood.blockID, 5, 3);

		return true;
	}
}